(*                                  ===========Probelm Statement=============
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms. 
 *)

 (* max --> upto which u want the sum*)
local
  fun start(a ,b , sum , max ) = if(b > max) then(
        sum
    )else(
        if(b mod 2 = 0) then(
            start(b, a+b ,sum+b , max)
        )else(
            start(b,a+b, sum , max)
        )
    )
in
  fun main(max) = start(0,1 , 0 ,max)
end

val ans = main(4000000)
